# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       qmlclock

# >> macros
# << macros

Summary:    QML clocks application
Version:    0.0.0
Release:    1%{?dist}
Group:      Applications/System
License:    BSD
URL:        http://github.com/nemomobile/qmlclock
Source0:    %{name}-%{version}.tar.gz
Requires:   nemo-qml-plugin-time-qt5
Requires:   nemo-qml-plugin-alarms-qt5
Requires:   qt-components-qt5
Requires:   mapplauncherd-booster-qtcomponents-qt5
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  pkgconfig(QtGui)
BuildRequires:  mapplauncherd-qt5 >= 1.1.0
BuildRequires:  desktop-file-utils
BuildRequires:  pkgconfig(qdeclarative5-boostable)
BuildRequires:  pkgconfig(Qt5Quick)

%description
Clocks application written using QML. Implements UI for end user to handle alarms.

%prep
%setup -q

%build

qmake -qt=5 -recursive
make %{?jobs:-j%jobs}

%install
rm -rf %{buildroot}
%qmake_install

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/qmlclock
%{_datadir}/applications/qmlclock.desktop

